### PR TITLE
Create Minutes for 4-8-2021

### PR DESCRIPTION
**Pull request by DryCreations**
# List Any Relevant Actions or Tasks

## Actions

N/A

## Tasks

N/A

# Description of Changes

+ Created minutes for the 4-8-2021 meeting

# Relevant Artifacts

N/A

# Other Comments

N/A

### CODE REVIEW

**Review by Cassandra-Mae-Patel — APPROVED** [review]
I think that in Question 6, we need to add the decision that "our team agreed to add more user stories because the team came to the conclusion that more tasks are needed."
I suggest that because I see that we don't get points for the "N/A" answer .  Let me know what are your views for that.
 Otherwise, I think it is good to be merged in the  main.

**Review by leonard-parker5 — APPROVED** [review]
Looks good. Action 39 & 51 are technically done, I just haven't put up a pull request yet. Was going to solve some minor conflicts with the branches we were looking to merge during the meeting and then put them up. Not sure what our criteria is for a "completed" task but you can move them to completed if you'd like. Not a big deal otherwise.

**Comment by DryCreations** [comment]
> I think that in Question 6, we need to add the decision that "our team agreed to add more user stories because the team came to the conclusion that more tasks are needed."
> I suggest that because I see that we don't get points for the "N/A" answer . Let me know what are your views for that.
> Otherwise, I think it is good to be merged in the main.

I don't think it's necessary, but if more people chime in we can add it. The minutes requirement in the grade book is:

> To earn full credit, you must be identified as "present" in Minutes for at least 5 separate meetings, and the Minutes must document your non-trivial contribution in the Project. Completion of Action Items that are documented in the Minutes can be used to document your contribution.

so it's not based on the actual grade received on the minutes quiz itself. I don't think it's necessary to add extra content to get credit for the last question. Based on class today, we get credit if any points are awarded for the minutes quiz.

**Comment by Cassandra-Mae-Patel** [comment]
Okay, that makes sense. Thanks for the clarification.

**Pull request merged**
