### PR TITLE
Action 79: Test Coverage Grading Requirements

### PR DESCRIPTION
**Pull request by DryCreations**
# List Any Relevant Actions or Tasks

## Actions

Action 79: Ensure the team meets the Test Coverage requirements by modifying the contents of /grading to reflect our completion of the criteria.

## Tasks

N/A

# Description of Changes

Modified the contents of /grading to include links to all relevant artifacts proving completion of the test coverage grade items.

# Relevant Artifacts

N/A

# Other Comments

N/A

### CODE REVIEW

**Review by bobobo77 — COMMENTED** [review]
Seems fine. Markdown requirements look valid

**Review by hgongloff — APPROVED** [review]
Looks good to me!

**Review by bobobo77 — APPROVED** [review]

**Review by PythonProgramm3r — APPROVED** [review]
This looks great and included the junit path.

**Review by Cassandra-Mae-Patel — APPROVED** [review]
Those files are pretty well described.
Good Job!

**Pull request merged**
