### PR TITLE
Cvw Doxygen skeleton

### PR DESCRIPTION
**Pull request by charleswitherspoon**

### CODE REVIEW

**Review by PythonProgramm3r — CHANGES_REQUESTED** [review]
Do a pull to solve these merge issues.

**Review by DryCreations — CHANGES_REQUESTED** [review]
afaik all other branches so far have been using the `\` notation for doxygen instead of `@`, i'd suggest changing yours, or we can discuss at a meeting what standard we will use.

Other branches are also using the notation `t1_1` with a lowercase `t` instead `T1_1`.

A Doxyfile was added already in another pull request, this one is probably unnecessary, and can be removed.

changes to tasks.md, and the doxyfile can most likely be dropped. And the gitignore changes can be worked in. This should resolve merge conflicts.

Based on changes to the code since this was created, PDFarea may also be redundant as this has taken a while to get merged.

**Comment by charleswitherspoon** [comment]
I've removed the overwritten tasks.md and Doxyfile with the main branch versions, and I've updated .gitignore to include distinct entries from each file. I've also removed the PdfArea class.

I have also edited the main Doxyfile to have an output directory of "doxygen" rather than ".\doxygen" as it was literally creating a folder named ".\doxygen"

**Review by DryCreations — APPROVED** [review]

**Comment by DryCreations** [comment]
Changes are approved for me, after merging another approved pull request some other conflicts popped up. But it should be trivial. 

The doxyfile from yours can be pushed into main.  the changes to the pom.xml should mostly be able to be pushed into main without issues. I think the issue is from an additional dependency being added: 


```
<dependency>
    <groupId>org.swinglabs</groupId>
    <artifactId>pdf-renderer</artifactId>
    <version>1.0.5</version>
</dependency>
```

**Review by DryCreations — APPROVED** [review]

**Review by PythonProgramm3r — APPROVED** [review]

**Pull request merged**
