### PR TITLE
ccp action 34 fixed and made compatible with main

### PR DESCRIPTION
**Pull request by Cassandra-Mae-Patel**
# List Any Relevant Actions or Tasks

## Actions

Action 34

# Description of Changes

- Right click on the selected image provides context menu to select to option to link the object [see "img 34.1" in the Relevant Artifact Section]
- On selecting the option "Link Object" prompts the dialog box [see "img 34.2" in the Relevant Artifact Section]
- After providing the proper link click ok... Now, the link is successfully attached to the shape. To verify this press down the "Ctrl" key and simultaneously click the shape. This will take you to the link provided .

# Relevant Artifacts
[img 34.1]
image

[img 34.2]
image

# Other Comments

- Removing the line of code "_drawingToolBar.setLayoutY(50);" and clicking on Drawing Menu gives me result as below (Does not display drawing toolbar):
image

-keeping the line of code gives me the output as desired, i.e., drawing toolbar visible at the top, as shown in the [img 34.1]

[NOTE:] For the sake of this pull request and the comment by Hayden  https://github.com/DryCreations/pdfproject/pull/45#discussion_r614442484
the line of code _drawingToolBar.setLayoutY(50) is removed.
While taking the screenshot [img 34.1] the line of code was not removed.

### CODE REVIEW

**Review by charleswitherspoon — CHANGES_REQUESTED** [review]
I left a comment on the other pull request before realizing this pull request was made to fix the changes. If this branch is replacing the other one, we should close the other pull request and delete that branch.

To summarize the comments left on the other pull request:
- I agree with Hayden that we should create a Linkable interface, rather than adding "linking" functionality to the Selectable interface; however, this can be a separate task.
- You've removed the testing line that moved the toolbar down, so no issues there.
- When creating a link, the link text is placed in the top left corner of the page. Each additional link has it's link text placed on top of the previous links' text.

The only changes I see that need to be made are finding a way to prevent the link text from showing up in the top left corner of the screen.

Here's a screenshot of two created links for google and youtube:
google_and_youtube

**Review by leonard-parker5 — CHANGES_REQUESTED** [review]
When testing an earlier version of this functionality I also had an issue where the toolbar was lower than it needed to be. Removing that line has fixed that so that's good.

However like Charles stated there is an issue where links are shown at the top left of the document. Once those are removed though this should be good to merge.

Untitled

**Comment by Cassandra-Mae-Patel** [comment]
Charles and Parker, thank you for pointing that out. That link text was not visible on my screen but, I figured out what the problem was with those link text. Please review it once more and let me know if there are still any problems.

**Review by leonard-parker5 — APPROVED** [review]
Tested again after the new commits. Problem with the lowered toolbar remains resolved and the previously stated problem with links showing at the top left of the page has also been resolved. The code looks good as well, nothing stands out as needing changes. Looks good to merge!

Images confirming resolved issue:

**Review by bobobo77 — APPROVED** [review]
I like what was added to Select.java. Everything seems in order.

**Review by charleswitherspoon — APPROVED** [review]

**Pull request merged**
