### PR TITLE
Adding junit, this is a running unit test class.  

### PR DESCRIPTION
**Pull request by PythonProgramm3r**
# List Any Relevant Actions or Tasks

## Actions
Added junit testing and a few tests. 
...

## Tasks
Implement junit testing
...

# Description of Changes
Added junit testing 
...

# Relevant Artifacts
Selenium
Junit 
MoveStackTest.java 
...

# Other Comments
I also added a few unit tests to this item. 
...

### CODE REVIEW

**Review by DryCreations — COMMENTED** [review]
I'm not opposed to merging this, as this does add junit testing. However, if I recall correctly, we discussed running these tests automatically using a github workflow.

And to clear any misconceptions about the pull request template, we are referencing the specific action numbers we put in the minutes, not just a description of what you did. Artifacts are also meant to be any screenshots, or generated files, relevant to showing it is completed or tested, not what was used in implementing it.

**Comment by PythonProgramm3r** [comment]
Yes, I understand this isn't the automated testing on github entirely. This is a beginning step as including unit tests is part of ensuring that github's verifies that the unit tests are passing. I think that detailing the additional pieces of this user story / understanding the entire user story is imperative for this entire user story to get done.

**Review by Cassandra-Mae-Patel — APPROVED** [review]
I agree with William that this could be used to build and create Github workflow to automate testing. And for the test that you have written, I think it is great Move Stack test! 
Also, a lot of our work include implementation of GUI where screenshots can work as test artifacts. I think this test covers nice amount of  rest of our work.

**Review by charleswitherspoon — APPROVED** [review]
I went ahead and merged with origin to be safe. This doesn't quite capture the automation task, but this branch is necessary to merge for other actions. We'll need to rework the task to add github automation.

**Pull request merged**
