### PR TITLE
Action 63: Added Doxygen Comments to Public Methods

### PR DESCRIPTION
**Pull request by charleswitherspoon**
# List Any Relevant Actions or Tasks

## Actions
Action 63

## Tasks
N/A

# Description of Changes
Added Doxygen documentation to public methods for TriConsumer, SelectOccurrences, ExtractCode, and NavigationPane classes

# Relevant Artifacts
N/A

# Other Comments
Switch to this branch and generate the Doxygen files to see documentation.

### CODE REVIEW

**Review by DryCreations — APPROVED** [review]
These comments look good, I believe they cover all public methods in the assigned classes.

**Review by hgongloff — APPROVED** [review]
All public methods seem to be documented correctly. Nice Job!

**Review by Cassandra-Mae-Patel — APPROVED** [review]
The documentation looks pretty good.
Nice job!

**Review by PythonProgramm3r — APPROVED** [review]
These comments are descriptive.

**Review by bobobo77 — APPROVED** [review]

**Pull request merged**
