### PR TITLE
ccp action49 updated

### PR DESCRIPTION
**Pull request by Cassandra-Mae-Patel**
# List Any Relevant Actions or Tasks

## Actions

Action 49

# Description of Changes

Added Test artifacts from Action 36 to Action 47

# Other Comments
[NOTE:]
For any pull request that is made after this particular pull request which is associated with certain task and gets approved,  a separate test Artifact is to be made for it using the `test_artifact_Template` and stored in `Test_Artifacts` directory after the pull request is merged.

### CODE REVIEW

**Review by DryCreations — APPROVED** [review]
These additions look good, thank you for adding more descriptions of our test artifacts.

Since this looks like it was branched off of https://github.com/DryCreations/pdfproject/pull/45

as long as that get's approved and merged, I have no issues with the changes relevant to test_artifacts. 

I think in the future it would make sense to only branch off of unapproved pull requests, if and only if you are building off of the changes that were made in it. Since the markdown files you added here are unrelated to the code from before, they could have been separate branches without issue.

**Review by leonard-parker5 — APPROVED** [review]
The template looks good and I think includes all the necessary information for further documenting the testing for our actions.  Extremely minor quibble but you could call the Screenshot header "Screenshot and its title" instead of using the word "description" since you technically only describe the screenshot under the next header.

Also like Hayden mentioned we should make sure #45 is merged in before this to avoid merging any unapproved code.

**Review by PythonProgramm3r — APPROVED** [review]
These test templates give everyone an objective styling for our group, great job. This was demoed while we were doing a sprint review, and also seems valid for logging do/undo. Waiting to merge this as other reviewers mentioned.

**Review by DryCreations — CHANGES_REQUESTED** [review]
If you make changes to the code on the other PR https://github.com/DryCreations/pdfproject/pull/45#discussion_r614465394

make sure the changes are also reflected here, or remove the code changes from this PR.

**Review by hgongloff — APPROVED** [review]
Looks great for displaying all the documentation for testing our actions. Great job!

**Review by DryCreations — APPROVED** [review]

**Pull request merged**
