### PR TITLE
Action 57 - Write 1 user story to add to backlog, and break down into tasks

### PR DESCRIPTION
**Pull request by leonard-parker5**
Added user story 19 and relevant tasks.

# List Any Relevant Actions or Tasks

## Actions

Action 57

## Tasks

None

# Description of Changes

Created new user story requesting increased GUI accessibility and broke the user story down into relevant tasks.

# Relevant Artifacts

 - User Story 19 - As a user, having more buttons in the toolbox and menu for easily accessing existing functionalities would increase the accessibility of the program.
 - Tasks:
 - 19.1 Implement increased accessibility into the GUI via additional buttons and menu items
 - - 19.1.1 Implement a save button to the toolbox for saving PDFs
 - - 19.1.2 Implement a new document button to the toolbox for creating new PDFs
 - - 19.1.3 Implement an undo/redo MenuItem in the Edit Menu for accessing undo/redo functionality
 - 19.2 Implement increased accessibility into the GUI via keyboard shortcuts
 - - 19.2.1 Implement a keyboard shortcut for saving a document
 - - 19.2.2 Implement a keyboard shortcut for creating a new document
 - - 19.2.3 Implement a keyboard shortcut for the undo/redo feature

# Other Comments

Feel free to post a suggestion if there's anything simple you'd like to see added to the GUI that could be added as a task. This user story was mostly written to give smaller supplemental tasks for anyone working on a larger feature.

### CODE REVIEW

**Comment by DryCreations** [comment]
This looks great, and I think this is a great and very achievable  user story.

My only critique would be that I think we might want to break apart the toolbox buttons and keyboard shortcuts into different tasks.

I think 19.1.x could be about toolbox buttons. and 19.2.x could be focused on keyboard shortcuts.

**Comment by leonard-parker5** [comment]
That's a good idea. I'll make those changes now.

**Review by Cassandra-Mae-Patel — APPROVED** [review]
The tasks are very well defined for this user story.
It would be nice to add a reorder page option in the Edit Menu to facilitate the reordering of the pages without drag and drop functionality.
Also,  implementing an option in  Insert Menu to add a Table would be great too.

**Review by DryCreations — APPROVED** [review]

**Review by bobobo77 — APPROVED** [review]
Comments look cohesive, and we just looked at them

**Pull request merged**
