### PR TITLE
Action 47: Allow user to open existing documents

### PR DESCRIPTION
**Pull request by DryCreations**
Added a button under `File -> Open Document` to open existing pdf documents

While testing this it has come to my attention that the exported pdf from itext7 is slightly malformed, likely the same issue here [https://stackoverflow.com/questions/61364972/why-is-my-xref-table-corrupt-after-removing-or-adding-annotations](https://stackoverflow.com/questions/61364972/why-is-my-xref-table-corrupt-after-removing-or-adding-annotations)

It is displayable by most pdf readers, however the one we use to display pdfs will not work. So we cannot reopen pdf's exported by our own application. To solve this it seems modifying itext7 code would be necessary. Or we would need some way to detect the malformed xref table and fix it when we read a file.

otherwise opening pdf's that are not malformed works fine.

### CODE REVIEW

**Review by charleswitherspoon — COMMENTED** [review]
Changes look good. I was able to open a PDF document and have it displayed. We can write up another task for properly exporting to PDF later if we need. 

We should decide if we want the background to be the test pdf upon opening the application; if not, I suggest a blank canvas unless the user opens a PDF document.

Also, going forward, we might need to start removing any commented out code before making our pull requests to avoid clutter.

**Review by charleswitherspoon — APPROVED** [review]

**Review by leonard-parker5 — APPROVED** [review]
After testing I was able to get it to work as intended. Changes look good as well.

I agree with Charles on the commented out code. When working on my tasks I noticed a decent amount in the App file particularly. I was considering writing up a User Story to touch up the GUI and add more buttons to the tool box and menu to increase accessibility of the functionalities we currently have implemented. Getting rid of the commented out and unnecessary code could be a part of that as well.

Untitled

**Comment by Cassandra-Mae-Patel** [comment]
This works fine on my end in terms of opening the existing pdf . But the page seems cropped from the top end.
the original pdf: 
image

how it looks from our end:
image

and on maximizing the window, it looks something like this:
image

I don't know if anyone else faces the same situation.

**Review by Cassandra-Mae-Patel — APPROVED** [review]
Works exactly as expected. Just that the pdf seems to be little cropped from the top end and a bit malformed.. I think that's what you meant in the comment.
Hence, approved.

**Pull request merged**
