### PR TITLE
Keeping track of Sprint velocity [till 3rd Sprint]

### PR DESCRIPTION
**Pull request by Cassandra-Mae-Patel**
# List Any Relevant Actions or Tasks

## Actions

Action 60

# Description of Changes

- A template to keep track of Sprint, a guide to calculate sprint velocity and separate files for Sprint 1, 2 and 3 are created. 
-  Calculated Sprint Velocity till 3rd Sprint.

# Other Comments

There will be 2 more Sprints added later as we move forward in this course. 
 As we document these sprints make sure to  reflect those changes in the  `Sprint Velocity.md`  file [the calculations]

### CODE REVIEW

**Review by leonard-parker5 — APPROVED** [review]
The templates look good and the files generated for the sprints that we've completed already look good as well!

One thing that might be worth changing is adding the end date of the sprint to the template as well. If you look at one of the sprint documents you see the start date but don't have any indication of when the sprint ended unless you look at the next sprint documents start date.

So instead of [03/18/2021] we could have [03/18/2021 - 03/25/2021].

Having both on one document could help be more descriptive.

**Review by DryCreations — APPROVED** [review]
These sprints seem to be accurate as far as I can tell.

I will reiterate what I said in another PR, because it is similar https://github.com/DryCreations/pdfproject/pull/50#pullrequestreview-637208227

but, I think in the future we should make sure to only branch off of unapproved branches if you are building off those changes, and we should clearly note that it relies on another PR getting approved in the comments as we don't want to accidentally merge the contents of the other PR. The code that is included in the changes is unrelated to the task of adding these markdown files, I think it would've made more sense to branch from main for this.

As long as PR https://github.com/DryCreations/pdfproject/pull/45 gets merged first, I have no issue with this branch getting merged.

**Review by hgongloff — APPROVED** [review]
Looks great! All the points seem accurate to me as well

**Review by DryCreations — CHANGES_REQUESTED** [review]
If you make changes to the code on the other PR https://github.com/DryCreations/pdfproject/pull/45#discussion_r614465394

make sure the changes are also reflected here, or remove the code changes from this PR.

**Review by DryCreations — APPROVED** [review]

**Pull request merged**
