### PR TITLE
complete minutes for 18th March

### PR DESCRIPTION
**Pull request by Cassandra-Mae-Patel**
Just in case you haven't submitted minutes for 3/18.

- This is what I had on W10 Quiz.. Hope this helps

### CODE REVIEW

**Review by PythonProgramm3r — APPROVED** [review]
This is approved, but a few areas were missing.

**Comment by Cassandra-Mae-Patel** [comment]
> This is approved, but a few areas were missing.

Can you please elaborate which areas are missing so I can correct what I had? 
And if you are talking about Question 5, I didn't put anything it it because that is what we usually answer from Question 3 and I think copying it would be creating redundancy.

Thanks for the review!

**Review by PythonProgramm3r — APPROVED** [review]
I meant that a few of these tasks were unmodified ( past deadline ) and possibly think these were no longer important to put onto this document.

**Comment by Cassandra-Mae-Patel** [comment]
> I meant that a few of these tasks were unmodified ( past deadline ) and possibly think these were no longer important to put onto this document.

Ah, I see.  I have adjusted those dates for the tasks I was sure about. But, if there is something different you had let me know, and I'll adjust the minutes I submitted.

**Comment by DryCreations** [comment]
Thank you for this, it looks good.

**Review by DryCreations — APPROVED** [review]

**Pull request merged**
